#**BASIC ARRAY OPERATIONS**

1. Create a 3x3 array filled with random integers between 0 and 10. Calculate the sum, mean,
and standard deviation of the array.


In [1]:
import numpy as np

In [2]:
arr1 = np.random.randint(0, 11, size=(3, 3))
print("3x3 random array:\n", arr1)
print("Sum:", arr1.sum())
print("Mean:", arr1.mean())
print("Std Dev:", arr1.std())

3x3 random array:
 [[ 0  2 10]
 [ 5  8  8]
 [ 7 10  4]]
Sum: 54
Mean: 6.0
Std Dev: 3.2998316455372216


2. Create a 1D array of 10 elements and compute the cumulative sum of the elements.

In [3]:
arr2 = np.random.randint(0, 10, size=10)
print("1D array:\n", arr2)
print("Cumulative sum:", np.cumsum(arr2))

1D array:
 [7 3 4 3 8 3 2 6 2 8]
Cumulative sum: [ 7 10 14 17 25 28 30 36 38 46]


3. Generate two 2x3 arrays with random integers and perform element-wise addition, subtraction, multiplication, and division.

In [4]:
arr3_1 = np.random.randint(0, 10, size=(2,3))
arr3_2 = np.random.randint(0, 10, size=(2,3))
print("2x3 array 1\n", arr3_1,"\n2x3 array 2\n",arr3_2)
print("Addition:\n", arr3_1 + arr3_2)
print("Subtraction:\n", arr3_1 - arr3_2)
print("Multiplication:\n", arr3_1 * arr3_2)
print("Division:\n", arr3_1 / arr3_2)

2x3 array 1
 [[2 2 0]
 [9 5 3]] 
2x3 array 2
 [[4 1 6]
 [3 2 5]]
Addition:
 [[ 6  3  6]
 [12  7  8]]
Subtraction:
 [[-2  1 -6]
 [ 6  3 -2]]
Multiplication:
 [[ 8  2  0]
 [27 10 15]]
Division:
 [[0.5 2.  0. ]
 [3.  2.5 0.6]]


4. Create a 4x4 identity matrix.


In [5]:
mat = np.eye(4)
print("Identity Matrix\n", mat)

Identity Matrix
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


5. Given an array a = np.array([5, 10, 15, 20, 25]), divide each element by 5 using broadcasting.


In [6]:
a = np.array([5, 10, 15, 20, 25])
print("a divided by 5:\n", a//5)

a divided by 5:
 [1 2 3 4 5]


# **ARRAY MANIPULATION**

6. Reshape a 1D array of 12 elements into a 3x4 matrix.

In [7]:
arr6 = np.arange(12)
reshape= arr6.reshape(3,4)
print("1D array:\n",arr6)
print("Reshaped 1D array into 3x4:\n",reshape)

1D array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped 1D array into 3x4:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


7. Flatten a 3x3 matrix into a 1D array.

In [8]:
mat7 =  np.arange(9).reshape(3,3)
flat7 = mat7.flatten()
print("Reshaped 3D array into 1D:\n",flat7)

Reshaped 3D array into 1D:
 [0 1 2 3 4 5 6 7 8]


8. Stack two 3x3 matrices horizontally and vertically.

In [9]:
mat8_1 = np.arange(9).reshape(3,3)
mat8_2 = np.arange(9,18).reshape(3,3)
h_mat = np.hstack((mat8_1,mat8_2))
v_mat = np.vstack((mat8_1,mat8_2))
print("Horizonatal stack:\n",h_mat)
print("Vertical stack:\n",v_mat)

Horizonatal stack:
 [[ 0  1  2  9 10 11]
 [ 3  4  5 12 13 14]
 [ 6  7  8 15 16 17]]
Vertical stack:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]


9. Concatenate two arrays of different sizes along a new axis.

In [10]:
arr9a = np.arange(3)
arr9b = np.arange(2)
concat_diff_len = np.concatenate((arr9a, arr9b), axis=0)
print("Concatenated different-length 1D arrays:", concat_diff_len)

Concatenated different-length 1D arrays: [0 1 2 0 1]


10. Transpose a 3x2 matrix and then reshape it to have 3 rows and 2 columns.

In [11]:
mat10 = np.arange(6).reshape(3, 2)
transposed = mat10.T
reshaped10 = transposed.reshape(3, 2)
print("Original 3x2:\n", mat10)
print("Transposed (2x3):\n", transposed)
print("Reshaped back to 3x2:\n", reshaped10)

Original 3x2:
 [[0 1]
 [2 3]
 [4 5]]
Transposed (2x3):
 [[0 2 4]
 [1 3 5]]
Reshaped back to 3x2:
 [[0 2]
 [4 1]
 [3 5]]


# **INDEXING AND SLICING**

11. Given a 1D array of 15 elements, extract elements at positions 2 to 10 with a step of 2.

In [12]:
arr11 = np.arange(15)
sliced = arr11[2:10:2]
print("Array:", arr11)
print("Sliced from 2nd position to 10th position with step 0f 2:", sliced)

Array: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Sliced from 2nd position to 10th position with step 0f 2: [2 4 6 8]


12. Create a 5x5 matrix and extract the sub-matrix containing elements from rows 1 to 3 and columns 2 to 4.

In [13]:
mat12 = np.arange(25).reshape(5, 5)
submat = mat12[1:3, 2:4]
print("\nQ12. 5x5 matrix:\n", mat12)
print("Sub-matrix rows 1:3, cols 2:4:\n", submat)


Q12. 5x5 matrix:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Sub-matrix rows 1:3, cols 2:4:
 [[ 7  8]
 [12 13]]


13. Replace all elements in a 1D array greater than 10 with the value 10.

In [14]:
arr13 = np.arange(6,16)
arr13_clipped = arr13.copy()
arr13_clipped[arr13_clipped > 10] = 10
print("Original:", arr13)
print("Clipped:", arr13_clipped)

Original: [ 6  7  8  9 10 11 12 13 14 15]
Clipped: [ 6  7  8  9 10 10 10 10 10 10]


14. Use fancy indexing to select elements from a 1D array at positions [0, 2, 4, 6].


In [15]:
arr14 = np.arange(20, 30)
fancy14 = arr14[[0, 2, 4, 6]]
print("Array:", arr14)
print("Fancy indexed [0,2,4,6]:", fancy14)

Array: [20 21 22 23 24 25 26 27 28 29]
Fancy indexed [0,2,4,6]: [20 22 24 26]


15. Create a 1D array of 10 elements and reverse it using slicing.

In [16]:
arr15 = np.arange(10)
reversed15 = arr15[::-1]
print("Original:", arr15)
print("Reversed:", reversed15)

Original: [0 1 2 3 4 5 6 7 8 9]
Reversed: [9 8 7 6 5 4 3 2 1 0]


# **BROADCASTING**

16. Create a 3x3 matrix and add a 1x3 array to each row using broadcasting.

In [17]:
mat16 = np.arange(9).reshape(3, 3)
row16 = np.array([10, 20, 30])
result16 = mat16 + row16
print("Matrix: (3x3)\n", mat16, "\nRow vector: (1x3)", row16)
print("Broadcast add:\n", result16)

Matrix: (3x3)
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
Row vector: (1x3) [10 20 30]
Broadcast add:
 [[10 21 32]
 [13 24 35]
 [16 27 38]]


17. Multiply a 1D array of 5 elements by a scalar value using broadcasting.

In [18]:
arr17 = np.array([1,2,3,4,5])
prod = arr17 * 5
print("Product of 1d array with scalar value:\n",prod)

Product of 1d array with scalar value:
 [ 5 10 15 20 25]


18. Subtract a 3x1 column vector from a 3x3 matrix using broadcasting.

In [19]:
mat18 = np.arange(9).reshape(3, 3)
col18 = np.array([[1], [2], [3]])
result18 = mat18 - col18
print("Matrix:\n", mat18, "\nColumn vector:\n", col18)
print("Broadcast subtract:\n", result18)

Matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 
Column vector:
 [[1]
 [2]
 [3]]
Broadcast subtract:
 [[-1  0  1]
 [ 1  2  3]
 [ 3  4  5]]


19. Add a scalar to a 3D array and demonstrate how broadcasting works across all dimensions.

In [20]:
arr19 = np.arange(18).reshape(2, 3, 3)
result19 = arr19 + 10
print("3D array shape:\n", arr19.shape)
print("3D array: \n",arr19)
print("After adding scalar 10:\n", result19)

3D array shape:
 (2, 3, 3)
3D array: 
 [[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]
After adding scalar 10:
 [[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


20. Create two arrays of shapes (4, 1) and (1, 5) and add them using broadcasting.

In [21]:
a20 = np.arange(4).reshape(4, 1)
b20 = np.arange(5).reshape(1, 5)
result20 = a20 + b20
print("Shape (4,1):\n", a20, "\nShape (1,5):\n", b20)
print("Broadcast result (4,5):\n", result20)

Shape (4,1):
 [[0]
 [1]
 [2]
 [3]] 
Shape (1,5):
 [[0 1 2 3 4]]
Broadcast result (4,5):
 [[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]]


# **VECTORIZED OPERATIONS**

21. Compute the square root of each element in a 2D array using vectorized operations.

In [22]:
mat21 = np.array([[1, 4, 9], [16, 25, 36]])
sqrt21 = np.sqrt(mat21)
print("Matrix:\n", mat21, "\nSquare roots:\n", sqrt21)

Matrix:
 [[ 1  4  9]
 [16 25 36]] 
Square roots:
 [[1. 2. 3.]
 [4. 5. 6.]]


22. Calculate the dot product of two 1D arrays of size 5.

In [23]:
a22 = np.array([1, 2, 3, 4, 5])
b22 = np.array([5, 4, 3, 2, 1])
dot22 = np.dot(a22, b22)
print("a =", a22, " b =", b22, "\ndot product =", dot22)

a = [1 2 3 4 5]  b = [5 4 3 2 1] 
dot product = 35


23. Perform element-wise comparison of two 1D arrays and return an array of boolean values indicating where the first array has larger elements.

In [24]:
a23 = np.random.randint(0,10,size=(1,5))
b23 = np.random.randint(0,10,size=(1,5))
comparison23 = a23 > b23
print("a =", a23, " b =", b23)
print("a > b:", comparison23)

a = [[9 5 6 5 4]]  b = [[1 1 7 7 8]]
a > b: [[ True  True False False False]]


24. Create a 2D array and apply a vectorized operation to double the value of each element.

In [25]:
mat24 = np.random.randint(1,10,size=(2, 3))
doubled24 = mat24 * 2
print("Matrix:\n", mat24, "\nDoubled:\n", doubled24)

Matrix:
 [[4 4 1]
 [8 8 7]] 
Doubled:
 [[ 8  8  2]
 [16 16 14]]


25. Create a 1D array of 100 random integers and compute the sum of all even numbers using vectorized operations.

In [26]:
arr25 = np.random.randint(0, 100, size=100)
even_sum25 = arr25[arr25 % 2 == 0].sum()
print("All even numbers from length of 100 elements\n",arr25[arr25 % 2 == 0])
print("Sum of even numbers in 100 random integers:\n", even_sum25)

All even numbers from length of 100 elements
 [66 82 92 94 84 46  4  0  2 96 92  8 30 64 88 38 42 14 36 94 48  4 12 54
 38 80 72 22 26 22 90 36 68 78  0 26 50 32 58 30 74 10 28 30 94]
Sum of even numbers in 100 random integers:
 2154


# **LINEAR ALGEBRA**

26. Create a 3x3 matrix and find its determinant.

In [27]:
mat26 = np.random.randint(1, 10, size=(3,3))
det26 = np.linalg.det(mat26)
print("Matrix:\n", mat26, "\nDeterminant:", det26)

Matrix:
 [[5 9 3]
 [4 1 5]
 [8 7 5]] 
Determinant: 90.0


27. Given a 2x2 matrix, compute its inverse and verify by multiplying with the original matrix to obtain the identity matrix.

In [28]:
mat27 = np.array([[4, 7], [2, 6]])
inv27 = np.linalg.inv(mat27)
identity_check27 = np.dot(mat27, inv27)
print("Matrix:\n", mat27, "\nInverse:\n", inv27)
print("Matrix * Inverse (should be identity):\n", np.round(identity_check27))

Matrix:
 [[4 7]
 [2 6]] 
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Matrix * Inverse (should be identity):
 [[ 1. -0.]
 [ 0.  1.]]


28. Calculate the eigenvalues and eigenvectors of a 2x2 matrix.

In [29]:
mat28 = np.array([[2, 0], [0, 3]])
eigenvalues28, eigenvectors28 = np.linalg.eig(mat28)
print("Matrix:\n", mat28)
print("Eigenvalues:", eigenvalues28)
print("Eigenvectors:\n", eigenvectors28)

Matrix:
 [[2 0]
 [0 3]]
Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


29. Solve the system of linear equations 2x + 3y = 5 and 4x + 6y = 10 using NumPy.


In [30]:
a29 = np.array([[2, 3], [4, 5]])
b29 = np.array([5, 10])
print("Coefficient matrix:\n LHS:", a29, " RHS:", b29)
try:
    solution29 = np.linalg.solve(a29, b29)
    print("Solution:", solution29)
except np.linalg.LinAlgError as e:
    print("Singular matrix error:", e)
    print("(The two equations are linearly dependent tends to infinite solutions.)")
    lstsq_solution, *_ = np.linalg.lstsq(a29, b29, rcond=None)
    print("Least-squares (minimum norm) solution:", lstsq_solution)

Coefficient matrix:
 LHS: [[2 3]
 [4 5]]  RHS: [ 5 10]
Solution: [2.5 0. ]


In [31]:
print("Example for singular matrix\n")
a29_1 = np.array([[2, 3], [4, 6]])
b29_2 = np.array([5, 10])
print("Coefficient matrix:\n LHS:", a29_1, " RHS:", b29_2)
try:
    solution29_a = np.linalg.solve(a29_1, b29_2)
    print("Solution:", solution29_a)
except np.linalg.LinAlgError as e:
    print("Singular matrix error:", e)
    print("(The two equations are linearly dependent tends to infinite solutions.)")
    lstsq_solution, *_ = np.linalg.lstsq(a29_1, b29_2, rcond=None)
    print("Least-squares (minimum norm) solution:", lstsq_solution)

Example for singular matrix

Coefficient matrix:
 LHS: [[2 3]
 [4 6]]  RHS: [ 5 10]
Singular matrix error: Singular matrix
(The two equations are linearly dependent tends to infinite solutions.)
Least-squares (minimum norm) solution: [0.76923077 1.15384615]


30. Perform Singular Value Decomposition (SVD) on a 3x3 matrix and reconstruct the original matrix using the SVD components.

In [32]:
mat30 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
U30, S30, VT30 = np.linalg.svd(mat30)
Sigma30 = np.zeros((3, 3))
np.fill_diagonal(Sigma30, S30)
reconstructed30 = U30 @ Sigma30 @ VT30
print("Original matrix:\n", mat30)
print("U:\n", U30)
print("Singular values:", S30)
print("VT:\n", VT30)
print("Reconstructed matrix:\n", np.round(reconstructed30, 8))

Original matrix:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]
U:
 [[-0.20933734  0.96438514  0.16167618]
 [-0.50384851  0.03532145 -0.86306956]
 [-0.8380421  -0.26213299  0.47850992]]
Singular values: [17.41250517  0.87516135  0.19686652]
VT:
 [[-0.46466755 -0.55375455 -0.69097031]
 [-0.83328635  0.00949949  0.55275999]
 [ 0.2995295  -0.83262576  0.46585022]]
Reconstructed matrix:
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8. 10.]]
